### ISSUE TITLE
FRAGMENT_REGEX is too greedy, breaks multiple links

### ISSUE THREAD

**Issue by dato** [benbalter/jekyll-relative-links#16]
I have the following in my Markdown source:

```
This is [a first link](doc.md#ref) and then [a second link](anotherdoc.md).
```

_a second link_ ends up pointing to `anotherdoc.md` directly.

I believe the following diff would help, but not sure if it would break anything else:

```diff
-    FRAGMENT_REGEX = %r!(#.+)?!
+    FRAGMENT_REGEX = %r!(#[^)]+)?!
```

but it would break fragments that include a literal `)` for reference syntax.

**Comment by dato** [comment]
Perhaps:

```diff
-    FRAGMENT_REGEX = %r!(#.+)?!
+    FRAGMENT_REGEX = %r!(#(?:[^)]+|.+$))?!
```

**Comment by benbalter** [comment]
@dato are you able to submit a Pull Request with the updated regex and an associated test to prevent a regression?

**Comment by dato** [comment]
#18, hope the TDD commits are okay.
