### ISSUE TITLE
.html extension ommited

### ISSUE THREAD

**Issue by nhoizey** [benbalter/jekyll-relative-links#17]
I use this permalink configuration:

```yaml
permalink: :year/:month/:title.html
```

But when I create a link with `[link text](markdown.md)`, the generated HTML link points to `markdown` instead of `markdown.html`.

Any way to change that? Maybe a setting I didn't notice?

Thanks.

**Comment by benbalter** [comment]
@nhoizey thanks for opening an issue. Have you tried the following:

```yml
permalink: :year/:month/:title:output_ext
```

Testing locally, the permalink structure you provided was parsed by Jekyll-core as invalid, resulting in the `template` for Pages being `/:path/:basename`. With the second version, it was properly parsed as `/:path/:basename:output_ext` and the relative permalink (which just calls `page.url`) was outputted as expected. I added an explicit test for this in https://github.com/benbalter/jekyll-relative-links/commit/1fd9a19ec3197d93e04c77b47291ded317cc06d5.

**Comment by nhoizey** [comment]
@benbalter that's strange, I didn't get any warning or error with this permalink.

It now works as intended with `:output_ext`, thanks!

**Comment by benbalter** [comment]
I *think* it silently cleans up the permalink (intended or not). Either way, you'll want the document, not the permalink structure to dictate the extension in case at any point you have a non-HTML page.

**Comment by nhoizey** [comment]
Indeed.

Thanks again.
