### ISSUE TITLE
Detect dead links (perhaps using Jekyll’s own {% link %}?)

### ISSUE THREAD

**Issue by dato** [benbalter/jekyll-relative-links#19]
Jekyll normally aborts the build if it finds a dead link such as `{% link nonexistant.md %}`.

This is very useful behavior (prevents publishing dead links), but it is lost when using jekyll-relative-links (which is a very useful plugin as well).

Perhaps… jekyll-relative-links could rewrite relative links to use `{% link ...md %}` instead of replacing in the URL directly?

I toyed with an initial patch, it seems to me it can be done, but there are one or two ugly corner cases (e.g. fragments, which are not supported by `{% link %}`).

I’d love to hear, in the first place, what the maintainers think of the “fail the build if there’s a dead relative link”.

Many thanks in advance.

**Comment by benbalter** [comment]
@dato interesting. I don't know that I'd expect the plugin to raise an error and fail loudly, but perhaps we could put a debug or warning level error to the build output?
