### ISSUE TITLE
Plugin not working on Pages

### ISSUE THREAD

**Issue by AsixJin** [benbalter/jekyll-relative-links#21]
Is there any reason why this would not be working? I've set up jekyll and added the necessary lines to  my gemfile and config. My links still go to ".md" instead of ".html". Might I be missing something?

**Comment by benbalter** [comment]
It should work. https://github.com/contact would likely be your best resource for getting help with GitHub Pages.

**Comment by AsixJin** [comment]
OK will do but just for my understanding...This plugin should allow me to write a link like this => [link](link.md) but still go to link.html on Github Pages?

**Comment by benbalter** [comment]
> This plugin should allow me to write a link like `[link](link.md)` but still go to link.html on Github Pages?

Yes!

**Comment by koddo** [comment]
Hello. The plugin also seem to not work when I use jekyll locally.

**Comment by benbalter** [comment]
If you require support with GitHub Pages (or replicating GitHub Pages locally), please contact [GitHub support](https://github.com/contact).
