### ISSUE TITLE
Reference-style links are not processed when tag definition is indented

### ISSUE THREAD

**Issue by adamvoss** [benbalter/jekyll-relative-links#24]
Given the following file:

```markdown
[This is a link][]


  [This is a link]: self.md
```

This HTML is generated:

```html
<p><a href="self.md">This is a link</a></p>
```

Notice that the resulting link goes to **self.md** instead of **self.html**.

If you remove the indentation in the final line of the markdown file (where the link destination is declared) the generated HTML correctly points to **self.html**

**Comment by janpio** [comment]
Did I understand correctly:
```
  [This is a link]: self.md
```
does not work.
```
[This is a link]: self.md
```
works and intended.

Correct?

**Comment by qwtel** [comment]
sounds like a `\s*` in the regex would fix this. should double check if leading whitespace is a valid markdown reference though

**Comment by adamvoss** [comment]
@janpio Your understanding is correct
