### ISSUE TITLE
url_for_path failing

### ISSUE THREAD

**Issue by pcolmer** [benbalter/jekyll-relative-links#26]
I'm using jekyll 3.5.1 and trying to use jekyll-relative-links to fix the problem of GitHub MD files not being linked properly when the pages are built.

When I try to build the site, I get:

    NoMethodError: undefined method `sub` for nil:NilClass

The stacktrace is:

    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:77:in `block in url_for_path'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:77:in `each'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:77:in `find'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:77:in `url_for_path'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:41:in `block in replace_relative_links!'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:36:in `gsub!'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:36:in `replace_relative_links!'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:29:in `block in generate'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:27:in `each'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-relative-links-0.4.1/lib/jekyll-relative-links/generator.rb:27:in `generate'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:178:in `block in generate'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `each'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `generate'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:72:in `process'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/command.rb:26:in `process_site'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:63:in `build'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:34:in `process'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
    /home/philip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/exe/jekyll:13:in `<top (required)>'
    /home/philip/.rbenv/versions/2.4.1/bin/jekyll:22:in `load'
    /home/philip/.rbenv/versions/2.4.1/bin/jekyll:22:in `<top (required)>'

If I add a print statement to url_for_path so that I can see what path is set to, it is:

    go/go/hackathon-mexico

and that link is coming from this file:

    ---
    title: 96boards Go Events
    permalink: /go/
    layout: empty-container-page-no-nav
    redirect_from:
    - /go/aosp/
    ---
    # 96boards Go Pages
    [Go Hackathon Mexico](/go/hackathon-mexico/)
    [Go Hackathon India Summer 2017](/go/hackathon-indiasummer2017/)
    [Go DragonBoard-410c Partnership Brazil](/go/db410c-partnership-brazil/)

Now, in the main jekyll directory, the tree structure includes:

    go
        hackathon-mexico
            README.md

I'm presuming from the nil error that p.relative_path is resolving to nil rather than a string, but I'm not a Ruby programmer so I'm struggling to figure out what is going wrong. I thought that the links might be broken (which is why the code is resolving to a nil) but *these* pages are actually building properly at the moment because the links don't end with a .md filename.

What can I do to debug this further? Is it a problem with the plugin or with the site I'm trying to build?

**Comment by benbalter** [comment]
@pcolmer Thanks for the bug report. Are you able to recreate the error in an empty site (e.g., by copying just the above file). I'm having trouble recreating this.

**Comment by pcolmer** [comment]
Hmm ... interestingly, copying just that directory into an empty site builds OK. I'm gradually adding more elements from the failing site but, to be honest, I'm struggling to think of what I can copy now that might be relevant to that folder and it still builds OK.

Is there anything I can add to the script to output information that might help determine why it is getting a nil object?

**Comment by pcolmer** [comment]
OK - progress!

It looks like there is something bad happening when the jekyll-minimagick plugin is included. If you take a clean site and add the following to the bottom of _config.yml:

    mini_magick:
        blog_thumbnail:
            source: _assets/images/blog
            destination: assets/thumbnails/blog
            resize: "200x200"
        project_thumbnails:
            source: _assets/images/projects
            destination: assets/thumbnails/projects
            resize: "200x200"

and the necessary steps to include "jekyll-minimagick" as a plugin, then building the site breaks on *your* code for some reason. Commenting out the above section (but leaving the plugin included) allows the site to build.

Does that have the desired result for you?

**Comment by benbalter** [comment]
@pcolmer thanks that's helpful. The issue is that minimagick extends `Jekyll::StaticFile` as `GeneratedImageFile ` and then adds them to `site.static_files`, but doesn't fully implement `Jekyll::StaticFile`. We can guard against a static file returning `nil` for `#url`, but the better solution would be for the upstream plugin to mirror https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb#L29-L38 in https://github.com/zroger/jekyll-minimagick/blob/master/lib/jekyll-minimagick.rb#L15-L23.

**Comment by benbalter** [comment]
Guarded against `target.url` being `nil` via 79a98e0.

**Comment by pcolmer** [comment]
@benbalter Unfortunately, it is the lack of relative_path in minimagick's extension of `Jekyll::StaticFile` that is breaking jekyll-relative-links. In other words, this line:

    target = potential_targets.find { |p| p.relative_path.sub(%r!\A/!, "") == path }

is where it is failing. Perhaps using `try` to protect against relative_path returning nil and causing sub to fail?

**Comment by benbalter** [comment]
@pcolmer since minimagick is extending but not fully implementing `Jekyll::StaticFile`, I think the better solution would be for minimagick to respect the public `Jekyll::StaticFile` API (so that it doesn't' interfere with other plugins that rely on `post.url`), rather than guarding against methods missing in every other plugin (and potentially Jekyll core).

**Comment by pcolmer** [comment]
Oh, I agree - I have raised an issue on their repository: https://github.com/zroger/jekyll-minimagick/issues/16.

**Comment by benbalter** [comment]
@pcolmer if for some reason they don't implement the change upstream, please reopen the issue here, and we can try to defensively code around what we can.
