### ISSUE TITLE
Links from normal pages to collections are broken

### ISSUE THREAD

**Issue by janpio** [benbalter/jekyll-relative-links#32]
I was just playing around with the new collections functionality, and seem to have broken something.

Project Source: https://github.com/janpio/jekyll-relative-links_test
Hosted on GH: https://janpio.github.io/jekyll-relative-links_test/ (Same result with `jekyll s` locally)

File structure looks like this:
```
.
├── _articles
│   ├── folder
│   │   └── test2.md
│   └── test.md
├── foo.md
├── index.md
```

`articles` is registered as a collection, the `collections` feature of `jekyll-relative-links` is enabled.

https://janpio.github.io/jekyll-relative-links_test/
https://janpio.github.io/jekyll-relative-links_test/foo.html
Note the 2 broken links to the "articles".

(via https://janpio.github.io/jekyll-relative-links_test/dump.html you get a list of all articles)

https://janpio.github.io/jekyll-relative-links_test/test
https://janpio.github.io/jekyll-relative-links_test/folder/test2
Note that here both the links to the pages and to the articles work.

Am I missing something or is this case not covered (yet)?

**Comment by benbalter** [comment]
@janpio the link is relative to the file on disk, not relative to the published path. E.g., is should be `_articles/test.md` not `test.md`. If you'd like to use the relative path to the resulting file, you should use `test` not `test.md` (and then will not need to use this plugin).

**Comment by janpio** [comment]
D'oh - of course.

**Comment by janpio** [comment]
Works perfectly at https://janpio.github.io/jekyll-relative-links_test/ now :) Thanks.

PR with more examples that would have made that clearer to my tired brain.
