### ISSUE TITLE
[welcome bot] CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by janpio** [benbalter/jekyll-relative-links#35]
Welcome bot links to non-existent file:
https://github.com/benbalter/jekyll-relative-links/blob/06c4fdc301c661653596e0016bd955df4cfa1070/.github/config.yml#L17
Can't PR fixed link as file doesn't exist at all.

**Comment by benbalter** [comment]
Wow. Good catch. Sorry about that. Thanks for opening an issue and letting me know. Adding a CONTRIBUTING file in https://github.com/benbalter/jekyll-relative-links/blob/master/docs/CONTRIBUTING.md.
