### ISSUE TITLE
Can't modify frozen String

### ISSUE THREAD

**Issue by pcolmer** [benbalter/jekyll-relative-links#40]
We're getting the above error when we try to build our site. The error is occurring at:

document.content.gsub!(LINK_REGEX) do |original|
(in replace_relative_links, line 47)

Having done some more research, it would seem that this isn't allowed with Ruby 2.3 and later. The oft-recommended solution is to call 'dup' on the content first then modify that duplicate copy but I don't know Ruby enough to unpick that from the do-loop.

Thanks.

**Comment by pcolmer** [comment]
OK, here is the fix:

      content = page.content.dup
      content.gsub!(LINK_REGEX) do |original|
        link_type, link_text, relative_path, fragment = link_parts(Regexp.last_match)
        next original if fragment?(relative_path) || absolute_url?(relative_path)

        if @config["verbose"] > 2
          puts "link_type=#{link_type}, link_text=#{link_text}, relative_path=#{relative_path}, fragment=#{fragment}"
        end

        path = path_from_root(relative_path, url_base)
        url  = url_for_path(path)

        if url
          replacement_text(link_type, link_text, url, fragment)
        else
          original
        end
      end
      page.content = content

It is just pulling the content out into a separate variable so that gsub! works, manipulating it and then putting it back into the page.

**Comment by benbalter** [comment]
@pcolmer are you able to submit a Pull Request with the proposed fix?

**Comment by pcolmer** [comment]
@benbalter I've done that but the CI checks are failing ... for what seems to be reasons outside of my control.
