### ISSUE TITLE
link text can't contains `]`

### ISSUE THREAD

**Issue by hax** [benbalter/jekyll-relative-links#42]
### Describe the bug

`[[test]](test.md)` and `[\[test\]](test.md)` won't be processed.

### Expected behavior

All valid markdown links should be processed.

### Additional context

It seems we should adjust the [regex in the source code](https://github.com/benbalter/jekyll-relative-links/blob/5e90d5307b54969079fe745d12ceb715bc4b8527/lib/jekyll-relative-links/generator.rb#L10) to fix it.

**Comment by andymond** [comment]
I'd like to tackle this bug!
