### ISSUE TITLE
Detect broken links

### ISSUE THREAD

**Issue by pgonzal** [benbalter/jekyll-relative-links#44]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Suppose I create a link like this:

```markdown
See [the help page](support/help.md) for more troubleshooting info.
```

### Describe the solution you'd like

If `./support/help.md` would be a broken link at runtime, then Jekyll should fail with an error at build time.

### Additional context

Currently **jekyll-relative-links** seems to silently emit a broken hyperlink.

**Comment by benbalter** [comment]
I would support a Jekyll Warn level build feedback, so users could see the broken link in the build output locally, but I don't think we should fail the entire build if one link is invalid, but we could build the entire site otherwise.

**Comment by pgonzal** [comment]
In our case it's a production web site, so why would we ever want to accept a PR that introduces a broken hyperlink?  If warning level feedback will cause the Travis build to fail (but not a local build), that's fine.  Otherwise, if the only way to fail Travils is to fail the build, then perhaps this validation could be an optional setting in `_config.yml`?

For the time being I am using Jekyll's `link` directive, which does fail the build if there is a broken link:

```markdown
[the help page]({{ site.baseurl }}{% link parent/folder/support/help.md %})
```

However, the syntax is pretty awkward.

**Comment by benbalter** [comment]
> In our case it's a production web site, so why would we ever want to accept a PR that introduces a broken hyperlink?

Completely agree. I might recommend checking out https://github.com/gjtorikian/html-proofer, which is intended to do just this (and can also validate non-relative links).

**Comment by pgonzal** [comment]
I did try that. It works pretty well on Linux, but I can't seem to get it to work on Windows. It's looking for **libcurl.dll** and won't accept it from typical places such as %PATH%.  I tried both 32-bit and 64-bit versions of the DLL.  

(I will also mention that the [website](https://curl.haxx.se/download.html) for obtaining Windows builds of **curl** seems a little sketchy. I feel uncomfortable instructing coworkers to download files from such a site.)

**Comment by pro-src** [comment]
@pgonzal

> (I will also mention that the website for obtaining Windows builds of curl seems a little sketchy. I feel uncomfortable instructing coworkers to download files from such a site.)

What's sketchy about it?

**Comment by pgonzal** [comment]
The website encourages users to download binaries from URLs pointing to random web sites, many of which are operated by a single individual.  Many of them are not even using HTTPS.  The website domain "haxx.se" even sounds like "hacker".

Unfortunately today malware is a sophisticated and organized enterprise.  At work employees should only be downloading executable binaries from sources that are obviously trustworthy (e.g. a recognized organization or company).

**Comment by pro-src** [comment]
I agree with all points, thanks a lot for the explanation.

As a work around, you could fork the repo, have the builds produced by AppVeyor, and link to the build artifacts. It's a very transparent approach as the source and the build process can be easily reviewed given the git history & public build logs.

**Comment by pro-src** [comment]
Plenty of eyes on this: https://github.com/curl/curl

**Comment by pro-src** [comment]
It doesn't get any safer than that assuming your coworkers trust you and/or can check hashes. Really though, you can see the irony in this, right? The binaries on that website are produced/published in a very similar way. Can't really trust anything on the internet with things like heartbleed in the wild, now can we? Lol

**Comment by pro-src** [comment]
@pgonzal

It doesn't get any safer than that assuming your coworkers trust you and/or can check hashes. Really though, you can see the irony in this, right? The binaries on that website are produced/published in a very similar way. Can't really trust anything on the internet with things like heartbleed in the wild, now can we? Lol

**Comment by pgonzal** [comment]
It would certainly be challenging to provide binaries for every last OS listed on the download page.  But for Mac and Windows, couldn't you rely on a free service such as appveyor or Travis CI to automatically build the binaries?  Even if you ended up hosting them with long URLs like `https://ci.appveyor.com/api/buildjobs/v87l17mja4axn1l...`, if they were documented on your download page as being official builds, that would be reasonably trustworthy.

For Linux, the binaries are already handled by the major distros.  The other OS's are mostly hobbyists or people who expect to compile their software from source code.

**Comment by pro-src** [comment]
Yup, It's FOSS so I don't see why It would be hard to use CI (for free) and deploy the binaries to Github Releases with hashes in the desc. Plenty of projects do this... Qbittorrent comes to mind.

**Comment by pgonzal** [comment]
BTW I investigated why the Windows SDK doesn't ship **libcurl.dll**. The problem is that this would imply ABI compatibility.  When a breaking change occurred, Windows would get stuck with an outdated version of the library.
