### ISSUE TITLE
Support absolute links

### ISSUE THREAD

**Issue by sieben** [benbalter/jekyll-relative-links#47]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I think this gem does not work when I got absolute links that finish with a `.md` 

### Describe the solution you'd like

I would like this gem to work with both absolute and relative link. At the current stage, it does not work with a link like [foo](/foo.md)

### Describe alternatives you've considered

I've tried to use permalink but those are very cumbersome to manage.

**Comment by benbalter** [comment]
Thanks to @krichardsson, this has been implemented via https://github.com/benbalter/jekyll-relative-links/pull/62.
