### ISSUE TITLE
Encoded Spaces Don't Work

### ISSUE THREAD

**Issue by dimipankratz** [benbalter/jekyll-relative-links#48]
### Describe the bug

MD files with links like this `/docs/space%20test.md` aren't converted.

### Steps to reproduce the behavior

Create a link like this `/docs/space%20test.md`. It is a valid relative link in MD on GH. However, it won't be converted, e.g., for GH pages.

### Expected behavior

I would expect that links with encoded spaces are also converted.

**Comment by sven-n** [comment]
Hi, I‘m having the same issue. I also have other encoded characters (brackets) in my links.
