### ISSUE TITLE
Relative links not resolved with include_relative

### ISSUE THREAD

**Issue by rmccue** [benbalter/jekyll-relative-links#5]
If I have an `index.md` with `{% include_relative _content.md %}`, and `_content.md` with `[Test](test.md)`, the relative link in the included content is not resolved.

**Comment by benbalter** [comment]
@rmccue to confirm, you have a relative link in an include file, and you'd like the link to resolve to the page relative to the parent page, or to the include? (sorry for the delay)

**Comment by b-admike** [comment]
@benbalter I have the same issue where all the relative links are working except one in an include block (https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb4/Testing-the-API.md). Any chance you can take a look?
