### ISSUE TITLE
Support Jekyll 4

### ISSUE THREAD

**Issue by kylekirkby** [benbalter/jekyll-relative-links#58]
Hi @benbalter,

Would you mind bumping the Jekyll requirement to allow v4 to be used? I can submit a PR if you'd like?

Best regards,

Kyle

**Comment by benbalter** [comment]
> I can submit a PR if you'd like?

Please do!

**Comment by kylekirkby** [comment]
Hi @benbalter,

Could you possibly push a new release to rubygems.org? :100:  

BR,

Kyle
