### ISSUE TITLE
Also process collections

### ISSUE THREAD

**Issue by FokkeZB** [benbalter/jekyll-relative-links#6]
Currently the plugin [only processes pages](https://github.com/benbalter/jekyll-relative-links/blob/master/lib/jekyll-relative-links/generator.rb#L25). I'd like it to process collections as well. This should probably only apply to collections that use the `output:true` property since otherwise you wouldn't know how to resolve the relative link (although we could just replace `.md` with `.html` and `/index.md` with `/`).

**Comment by FokkeZB** [comment]
Relates to https://github.com/benbalter/jekyll-optional-front-matter/issues/5

**Comment by benbalter** [comment]
Similar to https://github.com/benbalter/jekyll-optional-front-matter/issues/5 and https://github.com/benbalter/jekyll-titles-from-headings/issues/5, I'd be glad to review a PR that makes support opt-in when the collection is initialized.

**Comment by benbalter** [comment]
Implemented via https://github.com/benbalter/jekyll-relative-links/pull/28.
