### ISSUE TITLE
URLs with a fragment

### ISSUE THREAD

**Issue by nono** [benbalter/jekyll-relative-links#8]
Hi,

thanks for this plugin. It's a nice addition to Github pages.

I have a question: it seems that the plugin doesn't transform links to a markdown file when there is a fragment, is it expected? For example, if I have in the markdown `[TOC](README.md#table-of-contents)`, it will still be a link to the markdown file on github pages, not to the HTML file.

**Comment by benbalter** [comment]
> Doesn't transform links to a markdown file when there is a fragment, is it expected? 

That is not yet implemented, but would be a nice feature to add.

**Comment by nono** [comment]
Hi,

it's nice to see that you have started a PR. Can I help you to get it merged?

**Comment by benbalter** [comment]
I think https://github.com/benbalter/jekyll-relative-links/pull/9 should solve this... I just need to get tests to pass and I'd be glad to merge. Any help you could provide would be awesome.

**Comment by nono** [comment]
I've rebase your PR with the new commits and master and it looks like it's all good: #10.
