### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by brandonbirdj** [benbalter/jekyll-relative-links#90]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

It seems that this has not been released since 2019.

### Describe the solution you'd like

Could you release a new version.

### Describe alternatives you've considered

I did not see any new versions on https://rubygems.org/gems/jekyll-relative-links/versions/0.6.1

### Additional context

I am very interested in this change specifically https://github.com/benbalter/jekyll-relative-links/pull/71

**Comment by benbalter** [comment]
[Done!](https://github.com/benbalter/jekyll-relative-links/releases/tag/v0.7.0).
