### ISSUE TITLE
Some relative links are not converted

### ISSUE THREAD

**Issue by JJ** [benbalter/jekyll-relative-links#93]
### Describe the bug

In this code

```markdown
Posiblemente necesites [configurar tu
infraestructura](infraestructura/1.ConcienciaSituacional.md) antes de pasar al
nivel siguiente; cuando lo hagas, comienza con [él](2.Modelo.md).
```
that's translated to [this web page](https://jj.github.io/MPDA-IS/doc/1.Planificacion.html) (last paragraph, scroll down). The second URL is converted to its suffix-less equivalent... The first one is not.

### Steps to reproduce the behavior

I guess that paragraph by itself should fail. This paragraph:

```
 Se puede consultar [el
  documento de infraestructura](infraestructura/0.PRs.md), que muestra el punto
```

Fails to convert too. Maybe it's the fact that the reference to the URL is split in two lines?

### Expected behavior

It's a relative URL alright. It should be converted.

### Additional context

Here's the repo https://github.com/JJ/MPDA-IS It's using the GitHub pages, so that might translate to specific versions or processors.

**Comment by flanakin** [comment]
I noticed this when I started using collections. Are you using collections by any chance?

**Comment by monarchwadia** [comment]
I fixed this by setting `collections: true` in my `_config.yml`

```
relative_links:
  enabled:     true
  collections: true
  ```

**Comment by flanakin** [comment]
I just discovered that setting... I'm trying it now...

**Comment by JJ** [comment]
I'll try that, but what relationship is there between collections and these kind of links?

**Comment by janbrasna** [comment]
Duplicate of #61 

(known issue)

**Comment by JJ** [comment]
Closing in favor of #61
